name: RainbowArmor
version: 2.5
main: io.stealingdapenta.rainbow.Rainbow
author: StealingDaPenta
description: Fancy rainbow armor
api-version: 1.21

commands:
  rainbow:
    usage: /<command> <optional cycle speed>
    description: Equip / unequip rainbow armor
    default: op
  rainbowreload:
    description: Reload the configuration file without having to reboot the server.
    usage: /<command>

permissions:
  rainbow.use:
    description: Allow usage of /rainbow
    default: op
  rainbow.reload:
    description: Allow usage of /rainbowreload
    default: op