name: RainbowArmor
version: 3.0
main: io.stealingdapenta.rainbow.Rainbow
author: StealingDaPenta
description: Fancy rainbow armor
api-version: 1.21

commands:
  rainbow:
    description: Equip / unequip rainbow armor
    usage: /rainbow [optional cycleSpeed]
  rainbowreload:
    description: Reload the configuration file without having to reboot the server
    usage: /rainbowreload
  rainbowitem:
    description: Gives a rainbow armor set with optional animation speed
    usage: /rainbowitem [optional cycleSpeed]

permissions:
  rainbow.use:
    description: Allow usage of /rainbow
    default: op
  rainbow.reload:
    description: Allow usage of /rainbowreload
    default: op
  rainbow.item:
    description: Allow usage of /rainbowitem
    default: op
